config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :users, only: [:new, :create, :update, :destroy, :show]
    resources :groups, shallow: true do
      resources :memberships
      resources :articles do
        resources :versions, only: [:index, :new, :create, :show]
      end
  end

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :group
  has_many :versions

  def most_recent
    self.versions.last
  end

  def article_group
    self.group_id
  end

  def all_versions_by_author(user)
    self.versions.where(author_id: user.id)
  end

  validates :group_id, presence: true
  validates_numericality_of :group_id

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :articles
  has_many :memberships
  has_many :users, through: :memberships


  validates :name, uniqueness: true

  def has_member(user)
    self.users.find_by(id: user.id) != nil
  end
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :group
  belongs_to :user

  validates :group_id, presence: true
  validates :user_id, presence: true
  validates :access_level, presence: true
  validates :status, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :memberships
  has_many :groups, through: :memberships
  has_many :versions, foreign_key: :author_id

  has_secure_password
  validates :email, presence: true
  validates :email, uniqueness: { case_sensitive: false }
  validate :password_requirements

  def password_requirements
    unless password && password.length > 6 && password =~ /[!@#$%^&*]/
      errors.add(:password, "must be at least 6 characters in length and include one of (!@#$%^&*)")
    end
  end

end

app/models/version.rb
class Version < ActiveRecord::Base
  belongs_to :author, class_name: "User" # :)
  belongs_to :article

  validates :title, :presence => :true
  validate :article_exists

  def format_date
    month = self.created_at.month
    day = self.created_at.day
    year = self.created_at.year
    if self.created_at.hour > 12
      hour  = self.created_at.hour - 12
      time = self.created_at.strftime("#{hour}:%M %p")
    else
      time = self.created_at.strftime("%H:%M %p")
    end
    "#{month}/#{day}/#{year} #{time}"
  end

  def article_exists
    unless Article.find_by(id: self.article_id)
      errors.add(:article, "must be associated with an existing article")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # protect_from_forgery with: :null_session

  include SessionsHelper

  # helper_method :current_user

  # def current_user
  #   @current_user ||= User.find(session[:user_id]) if session[:user_id]
  # end


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show]
  def index
  end

  def create
    @group = Group.find_by(id: params[:group_id])
    @article = Article.new
    @group.articles << @article
    @version = Version.new(version_params)
    @article.versions << @version
    if @version.save
      @article.save
      flash[:success] = "Your new article was posted."
      redirect_to group_path(@group)
    else
      flash[:error] = "Invalid entry."
      render 'new'
    end
  end

  def new
    @group = Group.find_by(id: params[:group_id])
    @version = Version.new
  end

  def edit
  end

  def show
    @latest_version = Version.where(article_id: params[:id]).last
  end

  def update
  end

  def destroy
  end

  private
  def version_params
    params.require(:version).permit(:title, :body)
  end


  def find_article
    @article = Article.find(params[:id])
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    @groups = Group.all
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      flash[:success] = "Your group
      was created successfully."
      redirect_to group_path(@group)
    else
      flash[:error] = "Invalid entry"
      render 'new'
    end
  end

  def new
  end

  def edit
  end

  def show
    @membership = Membership.new
    @group = Group.find_by(id: params[:id])
  end

  def update
  end

  def destroy
  end

  def group_params
    params.require(:group).permit(:name)
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController


  def index
  end

  def create
    # p current_user
    # session[:user_id] = 2
    # p session[:user_id]
    # # p "USER ID:" + session[:user_id]
    @group = Group.find_by(id: params[:group_id])
    @membership = current_user.memberships.new(group_id: params[:group_id], user_id: current_user.id, access_level: "non-member")
    if @membership.save
      flash[:warning] = "Thank you for requesting membership to #{@group.name}. Your membership is pending approval."
      redirect_to root_path
    else
      render 'groups/show'
    end
  end

  def new
    # @membership = Membership.new
  end

  def edit
  end

  def show
    render 'show'
  end

  def update
  end

  def destroy
  end

  private

  # def membership_params
  #   params.require(:membership).permit(:group_id)
  # end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :current_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
       @user = User.new(user_params)
    if @user.save
      log_in(@user)
      flash[:success] = "Your account was successfully created!"
      redirect_to @user
    else
      render "new"
    end
  end

  def edit
  end

  def show
  end

  def update
    if current_user.update(user_params)
      flash[:success] = "You successfully updated your account!"
        redirect_to root_path
    else
      render "edit"
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:full_name, :password, :email)
  end

end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  before_action :find_article, only: [:index, :create, :new]
  before_action :find_version, only: [:show]

  def index
  end

  def create
    @version = Version.new(version_params)
    @article = Article.find_by(id: params[:article_id])
    @group = Group.find_by(id: @article.group_id)
    @version.article_id = @article.id
    p version_params
    if @version.save
      flash[:success] = "Your article was edited successfully."
      redirect_to group_path(@group)
    else
      flash[:error] = "Invalid entry."
      render 'new'
    end
  end

  def new
    p params
    @article = Article.find_by(id: params[:article_id])
    @version = @article.versions.last
  end

  def show
  end

  private
  def find_article
    @article = Article.find(params[:article_id])
  end

  def find_version
    @version = Version.find(params[:id])
  end

  def version_params
    params.require(:version).permit(:title, :body)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper

def log_in(user)
  session[:user_id] = user.id
end

def current_user
  @current_user ||= User.find_by(id: session[:user_id])
end

def log_out
  session.delete(:user_id)
  @current_user = nil
end

end

app/helpers/versions_helper.rb
module VersionsHelper
end

app/views/articles/new.html.erb
<h1>Create a new article for <%=@group.name%></h1>


<%= form_for @version, url: { action: "create" }, html: { class: "form-horizontal center form-container" } do |f| %>
  <div class="form-group">
    <%= f.label :title, "Title:", class: "col-md-4 control-label" %>
     <div class="col-md-4">
          <div id="new-article-title"><%= f.text_field :title, class: "form-control" %></div>
      </div>
  </div>

  <div class="form-group">
    <%= f.label :body, "Body:", class: "col-md-4 control-label" %>
     <div class="col-md-12">
          <%= f.text_area :body, class: "form-control", "data-provide" => "markdown", :rows => 10 %>
      </div>
  </div>

    <div class="form-actions">
      <%= f.submit "Create article", class: "btn btn-default btn-primary col-md-6" %>
    </div>

<% end %>

app/views/articles/show.html.erb
<div class="container">
  <%= render template: 'versions/_version_show', locals: {version: @article.most_recent }  %>

  <div class="more-info">
  <%= link_to "Back to Group", group_path(@article.group) %>
  <%= link_to "See All Versions", article_versions_path(@article) %>
  </div>
</div>

app/views/groups/index.html.erb
<div id="group-index-container">
  <h1>All Groups</h1>
  <h4>Click on a group to see its articles and request access</h4>

  <% @groups.each do |group| %>
    <ul>
      <li><a href="/groups/<%=group.id%>"><%=group.name%></a></li>
    </ul>
  <% end %>
  <p> <%= link_to "Add A New Group", new_group_path %></p>
  <p><%= link_to "Your Profile Page", current_user %><p>
</div>

app/views/groups/new.html.erb
<h1>Create a new group!</h1>

  <%= form_for :group,  url: { action: "create" }, html: { class: "form-horizontal center form-container" } do |f| %>
  <div class="form-group">
      <%= f.label :name, "Name:", class: "col-md-4 control-label" %>
     <div class="col-md-4">
          <%= f.text_field :name, class: "form-control" %>
      </div>
  </div>

  <div class="form-actions">
    <%= f.submit "Create Group", class: "btn btn-default btn-primary col-md-4" %>
  </div>

<% end %>

app/views/groups/show.html.erb
<div id="group-show-container">
  <h1><%= @group.name %> - Wiki Page</h1>

  <% if @group.has_member(current_user) %>
    <div id="gold-star">
      <svg viewBox="-30 -30 200 200" height="100" width="100">
        <polygon points="50,20 20,99 98,50 10,50 80,99" style="fill:gold;"/>
        Sorry, your browser does not support inline SVG.
      </svg>
    </div>

    <div id="group-members">
      <h3> Current Members (Click on a member's name to send that person an email)</h3>
      <% @group.users.each do |user| %>
      <ul>
      <li><a href="mailto:<%= user.email %>"><%= user.full_name %></a></li>
      </ul>
      <% end %>
    </div>

  <% else %>
    <%= form_for @membership, url: group_memberships_path(@group), method: :post do |f| %>
      <%= f.submit "Join This Group", class: "btn btn-default btn-primary col-md-4" %>
    <% end %>
  <% end %>

  <br>
  <h3><%= link_to "Add an article", new_group_article_path(@group) %> </h3>
  <h3>Articles:</h3>
  <ul>
  <% @group.articles.each do |article| %>
     <li><%= link_to article.versions.last.title, article_path(article) %> - updated <%= article.versions.last.created_at.strftime("%m/%d %H:%M %p") %> - <%= link_to "Edit article", new_article_version_path(article) %></li>


  <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>wikileagues</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Raleway:700' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>
</head>

<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">wikileagues</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><span class="sr-only">(current)</span></li>
        <% if current_user %>
        <li><%= link_to "My Profile", user_path(current_user)%></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Groups <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% current_user.groups.each do |group| %>
                <li><%= link_to group.name, group_path(group) %></li>
              <% end %>

            </ul>
          </li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
          <li><a href="/login">Login</a></li>
          <li><%= link_to "Signup", new_user_path %></li>
        <% else %>
          <li><a href="/logout">Hi <%=current_user.full_name %> (logout)</a></li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
<%= yield %>

</body>
</html>

app/views/memberships/show.html.erb
<h1>Thanks for joining</h1>

app/views/users/new.html.erb
<div class="container">
  <div id="site-title">signup</div>
</div>
<div class="container">
<%= form_for([@user]) do |f| %>
  <div class="field">
      <%= f.label :full_name, class: "col-md-4 control-label" %>
      <%= f.text_field :full_name, class: "form-control" %>
    </div>

    <div class="field">
      <%= f.label :email, class: "col-md-4 control-label" %>
      <%= f.text_field :email, class: "form-control" %>
    </div>

    <div class="field">
      <%= f.label :password, class: "col-md-4 control-label" %>
      <%= f.password_field :password, class: "form-control" %>
    </div>

    <div class="field actions">
      <%= f.submit "Sign Up", class: "btn btn-default btn-primary col-md-4"%>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class ="container">
  <h1>Welcome, <%= current_user.full_name %>!</h1>


  <% if current_user.groups.length > 0 %>
    <p>Your Groups:</p>

    <% current_user.groups.each do |group| %>
      <ul>
        <li><span id="users_groups"> <%= link_to "#{group.name}", group_path(group) %></span></li>
        <ul>
        <span id="contribution-text">Your contributions to this group:</span>
        <% group.articles.each do |article| %>
          <% article.all_versions_by_author(current_user).each do |version| %>
            <li><span id="authored_version_link"><%= link_to "#{version.title}", version_path(version) %></span></li>
          <% end %>
        <% end %>
        </ul>
      </ul>
    <% end %>

 <% else %>
    <p>You have no groups! Check out the link below and start requesting access now.</p>
 <% end %>
  <%= link_to "See All Brumbiki Groups", groups_path %><br>

</div>

app/views/versions/_version_show.html.erb
<h1><%=version.title%></h1>
<% if version.author %>
  <h5>created by  <%= version.author.full_name %> on <%= version.format_date %></h5>
<% end %>
<div class="body">

  <p><%= raw version.body %></p>
</div>

app/views/versions/index.html.erb
<div class="container">
  <h1> All Versions Of "<%= @article.most_recent.title %>"</h1>
  <ul>
  <% @article.versions.reverse.each do |version| %>

    <li><%=version.format_date %> <%= link_to "#{version.title}", version_path(version) %>
    <br></li>
    <br>
  <% end %>
  <br>
  <%= link_to "Back to Group", group_path(@article.group) %>
  <br>
  <%= link_to "Back to Article", @article %>
</div>
</div>

app/views/versions/new.html.erb
<h1>Edit <%=@article.versions.last.title%></h1>


<%= form_for @version, url: article_versions_path(@article), method: :post, html: { class: "form-horizontal center form-container" } do |f| %>
  <div class="form-group">
    <%= f.label :title, "Title:", class: "col-md-4 control-label" %>
     <div class="col-md-4">
          <%= f.text_field :title, class: "form-control" %>
      </div>
  </div>

  <div class="form-group">
    <%= f.label :body, "Body:", class: "col-md-4 control-label" %>
     <div class="col-md-4">
          <%= f.text_area :body, class: "form-control", :rows => 10 %>
      </div>
  </div>

    <div class="form-actions">
      <%= f.submit "Create article", class: "btn btn-default btn-primary col-md-6" %>
    </div>

<% end %>

app/views/versions/show.html.erb
<div class="container">
  <%= render template: 'versions/_version_show', locals: {version: @version }  %>
  <div class="group-link">
  <%= link_to "Back to Group", group_path(@version.article.group) %>
</div>
</div>

app/views/welcome/index.html.erb
<div id="home-page-container">
  <div id="site-title">wikileagues</div>
  <% if current_user %>
    <h3>Hello <%= current_user.full_name %>!</h3>
    <div class="index-buttons">
      <%= link_to "Log Out", logout_path, class: "btn btn-default btn-primary col-md-4" %><br>
    </div>
    <div class="index-buttons">
      <%= link_to "Go to Groups", groups_path, class: "btn btn-default btn-primary col-md-4" %><br>
    </div>
  <% else %>
    <div class="index-buttons">
      <%= link_to "Log In", login_path , class: "btn btn-default btn-primary col-md-4" %><br>
    </div>
    <div class="index-buttons">
      <%= link_to "Sign Up", new_user_path, class: "btn btn-default btn-primary col-md-4" %><br>
    </div>
  <% end %>
</div>